main_button_enter = '//a[@id="pp"]/b'
main_entry_email = '//input[@id="login"]'
main_entry_password = '//input[@id="psw"]'
main_button_submit = '//input[@name="submitbutton"]'
main_button_registration = '//a[@href="/register/"]'
reg_entry_email = '//td/input[@name="email"]'
reg_entry_nick = '//td/input[@name="nick"]'
reg_entry_password = '//td/input[@name="password1"]'
reg_entry_rep_password = '//td/input[@name="password2"]'#'//td/input[@type="password"]/following::td/input[@type="password"]/following::td/input[@type="password"]'
reg_radio_male = '//td/input[@name="gender"][@value="m"]'#'//td/input[@name="gender" and @value="m"]'
reg_radio_female = '//td/input[@name="gender"][@value="f"]'#'//td/input[@name="gender" and @value="f"]'
reg_button_finish = '//input[@type="submit"]/following::input[@type="submit"]'